
# This file was *autogenerated* from the file eg.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2)
print("Hello World")
print(_sage_const_2 **_sage_const_3 )


